# Generated by Django 6.0.1 on 2026-02-05 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_my', models.JSONField(default=dict)),
                ('field_op', models.JSONField(default=dict)),
                ('rows', models.IntegerField(default=10)),
                ('cols', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_battle_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
