# Generated by Django 6.0.1 on 2026-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seabattle', '0002_seabattle_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seabattle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='seabattle',
            name='field_my',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seabattle',
            name='field_op',
            field=models.JSONField(default=list),
        ),
    ]
