# Generated by Django 6.0.1 on 2026-02-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seabattle', '0003_alter_seabattle_options_alter_seabattle_field_my_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seabattle',
            name='ships',
            field=models.IntegerField(default=6),
        ),
    ]
