# Generated by Django 6.0.1 on 2026-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seabattle', '0004_seabattle_ships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seabattle',
            name='ships',
            field=models.IntegerField(default=5),
        ),
    ]
