# Generated by Django 6.0.1 on 2026-02-07 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seabattle', '0005_alter_seabattle_ships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seabattle',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sea_battle_player_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seabattle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sea_battle_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
