# Generated by Django 6.0.1 on 2026-02-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seabattle', '0006_seabattle_player_alter_seabattle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seabattle',
            old_name='field_my',
            new_name='field_player',
        ),
        migrations.RenameField(
            model_name='seabattle',
            old_name='field_op',
            new_name='field_user',
        ),
    ]
