# Generated by Django 6.0.1 on 2026-01-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='xxx',
            field=models.IntegerField(default=0),
        ),
    ]
