# Generated by Django 5.0 on 2026-01-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_at_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
