# Generated by Django 6.0.1 on 2026-01-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='xxx',
        ),
    ]
