# Generated by Django 6.0.1 on 2026-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_xxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eeee',
            field=models.IntegerField(default=0),
        ),
    ]
