# Generated by Django 6.0.1 on 2026-01-21 06:39

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_options_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.IntegerField(default=0, validators=[post.models.validate_not_zero]),
        ),
    ]
