# Generated by Django 6.0.1 on 2026-01-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
