# Generated by Django 6.0.1 on 2026-01-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_uuuu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='eeee',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uuuu',
        ),
    ]
