# Generated by Django 6.0.1 on 2026-01-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_eeee_remove_post_uuuu'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuuu',
            field=models.IntegerField(default=0),
        ),
    ]
