# Generated by Django 6.0.1 on 2026-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
