# Generated by Django 6.0.1 on 2026-01-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_uuuu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuuu',
        ),
    ]
