# Generated by Django 6.0.1 on 2026-01-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zzzzz',
            field=models.IntegerField(default=0),
        ),
    ]
