# Generated by Django 6.0.1 on 2026-02-03 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='document',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='operator',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='org',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='place',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('document', 'org', 'date'), name='unique_doc_org_date'),
        ),
    ]
