# Generated by Django 6.0.1 on 2026-02-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_item_name_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='document',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
