# Generated by Django 6.0.1 on 2026-02-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_document'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receipt',
            name='unique_doc_org_date',
        ),
    ]
