# Generated by Django 6.0.1 on 2026-02-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_remove_receipt_unique_doc_org_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='fiscal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
