# Generated by Django 6.0.1 on 2026-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fiscal',
            field=models.BigIntegerField(),
        ),
    ]
