# Generated by Django 6.0.1 on 2026-02-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipt_fiscal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='document',
            new_name='kkm',
        ),
    ]
