# Generated by Django 6.0.1 on 2026-02-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_rename_document_receipt_kkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
