# Generated by Django 6.0.1 on 2026-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_alter_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_sum',
            field=models.FloatField(default=0),
        ),
    ]
